$background = 0b0f0d
$onBackground = dee8e0
$surface = 0b0f0d
$surfaceDim = 0b0f0d
$surfaceBright = 252e29
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0f1512
$surfaceContainer = 141b17
$surfaceContainerHigh = 19211d
$surfaceContainerHighest = 1e2823
$onSurface = dee8e0
$surfaceVariant = 1e2823
$onSurfaceVariant = a3aea6
$outline = 6e7871
$outlineVariant = 404a45
$inverseSurface = f7faf6
$inverseOnSurface = 515653
$shadow = 000000
$scrim = 000000
$surfaceTint = a1d1b9
$primary = a1d1b9
$primaryDim = 94c3ac
$onPrimary = 1b4836
$primaryContainer = 2e5b48
$onPrimaryContainer = beeed5
$inversePrimary = 3b6854
$primaryFixed = bdedd5
$primaryFixedDim = afdfc7
$onPrimaryFixed = 1a4736
$onPrimaryFixedVariant = 386451
$secondary = b3ccbe
$secondaryDim = a6bfb1
$onSecondary = 2f453a
$secondaryContainer = 2a4036
$onSecondaryContainer = acc5b7
$secondaryFixed = cfe9da
$secondaryFixedDim = c1dacc
$onSecondaryFixed = 2e4439
$onSecondaryFixedVariant = 4a6055
$tertiary = ecfcff
$tertiaryDim = b3ecf5
$onTertiary = 2d676e
$tertiaryContainer = bbf5fd
$onTertiaryContainer = 235f66
$tertiaryFixed = bbf5fd
$tertiaryFixedDim = ade7ef
$onTertiaryFixed = 074c53
$onTertiaryFixedVariant = 2f6970
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 53806b
$secondaryPaletteKeyColor = 657c70
$tertiaryPaletteKeyColor = 488087
$neutralPaletteKeyColor = 747874
$neutralVariantPaletteKeyColor = 6f7973
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 53806b
$secondary_paletteKeyColor = 657c70
$tertiary_paletteKeyColor = 488087
$neutral_paletteKeyColor = 747874
$neutral_variant_paletteKeyColor = 6f7973
$term0 = 343434
$term1 = 769e00
$term2 = 7ce09c
$term3 = a3faaa
$term4 = 7bb6a1
$term5 = c6a844
$term6 = 90d8b1
$term7 = d0dbcc
$term8 = 9da599
$term9 = 85b900
$term10 = 7af5a6
$term11 = d5ffd4
$term12 = a7c8b7
$term13 = cec06b
$term14 = 9becbe
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = bae2ff
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = afd9a4
$yellow = dbf9da
$green = 9ef1c3
$teal = a6eed1
$sky = 99ebd2
$sapphire = 77d8c2
$blue = 5acfc0
$lavender = 85dcd3
$klink = 009887
$klinkSelection = 009887
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 50c14c
$kneutralSelection = 50c14c
$kpositive = 00c186
$kpositiveSelection = 00c187
$text = dee8e0
$subtext1 = a3aea6
$subtext0 = 6e7871
$overlay2 = 606963
$overlay1 = 515954
$overlay0 = 444b46
$surface2 = 363d39
$surface1 = 292e2b
$surface0 = 1a1f1c
$base = 0b0f0d
$mantle = 0b0f0d
$crust = 0a0e0c
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
