$background = 0b0f11
$onBackground = dee7ec
$surface = 0b0f11
$surfaceDim = 0b0f11
$surfaceBright = 252d32
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0f1417
$surfaceContainer = 141a1e
$surfaceContainerHigh = 1a2124
$surfaceContainerHighest = 1f272b
$onSurface = dee7ec
$surfaceVariant = 1f272b
$onSurfaceVariant = a4acb2
$outline = 6e777c
$outlineVariant = 41494e
$inverseSurface = f7fafc
$inverseOnSurface = 525658
$shadow = 000000
$scrim = 000000
$surfaceTint = a2cde2
$primary = a2cde2
$onPrimary = 174557
$primaryContainer = 2d586a
$onPrimaryContainer = c0e9ff
$inversePrimary = 3a6477
$primaryFixed = b5e0f6
$primaryFixedDim = a8d2e8
$onPrimaryFixed = 0f3f50
$onPrimaryFixedVariant = 315b6e
$secondary = b4cad6
$onSecondary = 2f434d
$secondaryContainer = 2a3e48
$onSecondaryContainer = adc3ce
$secondaryFixed = d0e6f2
$secondaryFixedDim = c2d8e4
$onSecondaryFixed = 2e424c
$onSecondaryFixedVariant = 4a5e69
$tertiary = c5d4ff
$onTertiary = 39486d
$tertiaryContainer = b7c6f2
$onTertiaryContainer = 303f64
$tertiaryFixed = b7c6f2
$tertiaryFixedDim = a9b8e3
$onTertiaryFixed = 1b2b4e
$onTertiaryFixedVariant = 39486d
$error = fa746f
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$term0 = 343434
$term1 = 8383ff
$term2 = 40dfec
$term3 = 75fcdd
$term4 = 7bb2c7
$term5 = 7aaee9
$term6 = 83d6e6
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 56f1ff
$term11 = c9fff3
$term12 = a5c6d0
$term13 = a2c0f7
$term14 = 89eafa
$term15 = ffffff
$klink = 1791bd
$klinkSelection = 1c91be
$kvisited = 0087cd
$kvisitedSelection = 0087cf
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = c794ff
$kpositive = 00bad3
$kpositiveSelection = 00bad5
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
