$background = 130d0a
$onBackground = f9e1d7
$surface = 130d0a
$surfaceDim = 130d0a
$surfaceBright = 372923
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a110e
$surfaceContainer = 211713
$surfaceContainerHigh = 281d18
$surfaceContainerHighest = 30231d
$onSurface = f9e1d7
$surfaceVariant = 30231d
$onSurfaceVariant = bca79e
$outline = 84716a
$outlineVariant = 54443e
$inverseSurface = fff8f6
$inverseOnSurface = 5d534f
$shadow = 000000
$scrim = 000000
$surfaceTint = f8b89d
$primary = f8b89d
$onPrimary = 603521
$primaryContainer = 754732
$onPrimaryContainer = ffdcce
$inversePrimary = 84533d
$primaryFixed = f8b89d
$primaryFixedDim = e9ab90
$onPrimaryFixed = 48220f
$onPrimaryFixedVariant = 6a3e29
$secondary = e6bead
$onSecondary = 553a2e
$secondaryContainer = 503529
$onSecondaryContainer = dfb7a6
$secondaryFixed = ffdbcd
$secondaryFixedDim = f5ccbb
$onSecondaryFixed = 54392d
$onSecondaryFixedVariant = 735447
$tertiary = fff2da
$onTertiary = 6d5922
$tertiaryContainer = ffe39e
$onTertiaryContainer = 64511b
$tertiaryFixed = ffe39e
$tertiaryFixedDim = f0d591
$onTertiaryFixed = 503f09
$onTertiaryFixedVariant = 6f5b24
$error = fa746f
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$term0 = 353433
$term1 = fd5a00
$term2 = ffbe8f
$term3 = ffe0cf
$term4 = b9ab66
$term5 = f19179
$term6 = ffbb7a
$term7 = eed3c5
$term8 = b49e94
$term9 = ff8858
$term10 = ffd5b8
$term11 = fff1eb
$term12 = dcbc93
$term13 = ffaa92
$term14 = ffd3ae
$term15 = ffffff
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5d51
$kvisitedSelection = cf5e4f
$knegative = e85922
$knegativeSelection = e85a1f
$kneutral = ff8b51
$kneutralSelection = ff8b4f
$kpositive = f49201
$kpositiveSelection = f39300
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
