-- Generated by nwg-displays on 2026-06-03 at 01:42:27. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "900x100",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1440x900@59.89",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
