.pragma library

var jokes = [
  "Linux: Because a PC is a terrible thing to waste.",
  "Windows: Just reboot. Linux: Just be root.",
  "In a world without fences, who needs Windows?",
  "Linux: No BSOD since 1991.",
  "Windows is for gaming, Linux is for doing.",
  "I tell Windows jokes, but they need restarting.",
  "With Linux, you have power. With Windows, the bill.",
  "Linux is user-friendly, it is just picky about friends.",
  "sudo rm -rf /windows",
  "Windows: It is not a bug, it is a feature.",
  "Linux: Where free means freedom, not free trial.",
  "Windows blue screens, Linux green screens.",
  "Linux users do not fix bugs, they recompile.",
  "Put a Windows user in front of Vim to freeze them.",
  "Windows: Press CTRL+ALT+DEL. Linux: uptime 1000 days.",
  "Linux: You own the system. Windows: Microsoft owns you.",
  "There is no place like ~/",
  "Linux: Freedom to break your own OS.",
  "Windows: 10GB update for emojis. Linux: 5MB kernel update.",
  "Windows asks Are you sure?, Linux just obeys.",
  "Linux: Works on a toaster. Windows: Needs 16GB RAM idle.",
  "Windows restarts for updates. Linux updates live.",
  "Old Windows PCs do not die, they get Linux installed.",
  "Windows: Searching for updates... Linux: pacman -Syyu",
  "Linux: Where every day is an adventure in bash.",
  "Windows is the OS. Linux is the lifestyle.",
  "Mac: Overpriced. Windows: Overloaded. Linux: Overpowered.",
  "Linux rule #1: If it is not broken, tweak it anyway.",
  "chmod 777 fixes everything... or breaks everything.",
  "Windows Defender: Scanned 0 files, found 0 threats.",
  "Linux kernel: Small, fast, powerful.",
  "Windows: Please do not turn off your computer. 1%...",
  "Linux: sudo make me a sandwich.",
  "Windows 11 requirements: NASA supercomputer.",
  "Linux: Configured in plain text. Windows: Registry nightmare.",
  "Vim: Easy to open, impossible to exit.",
  "Arch Linux users: By the way, I use Arch.",
  "Windows: Blue Screen of Death. Linux: Panic with details.",
  "Linux users spend 4 hours tweaking dotfiles to save 2 seconds.",
  "Windows Task Manager: (Not Responding)",
  "Linux: Neofetch on every terminal start.",
  "Windows: Telemetry active. Linux: Privacy respected.",
  "Linux: System uptime measured in years.",
  "Windows 10: Your PC will restart in 5 minutes.",
  "Linux: Customizing GRUB at 3 AM.",
  "Windows: Reinstalling display drivers again.",
  "Linux: Pipe anything to grep.",
  "Windows: Installing updates (3 of 457)...",
  "Linux: sudo chown -R me:me /world",
  "Windows: Edge wants to be your default browser.",
  "Linux: Custom kernel built in 42 seconds.",
  "Windows: Why is my fan spinning at 100%?",
  "Linux: htop shows 0.1% CPU usage.",
  "Windows: Running setup.exe... Linux: ./configure && make",
  "Linux: 1000 desktop environments, 0 bloatware.",
  "Windows: Automatic repair could not repair your PC.",
  "Linux: RTFM (Read The Fine Manual).",
  "Windows: Activate Windows watermark permanent.",
  "Linux: Freedom from licensing fees.",
  "Windows: The only virus with GUI.",
  "Linux: Where an error message actually tells you the error.",
  "Windows registry: A black hole for settings.",
  "A Windows admin's favorite key is F5. A Linux admin's is Tab.",
  "Windows: Because some people like to wait.",
  "Linux: Where you type 'make' and pray.",
  "Windows update: We are getting things ready for you.",
  "Linux is like a lightsaber. Windows is a blaster.",
  "Windows: Something happened.",
  "My Linux machine has been up longer than my relationship.",
  "Windows is great for playing solitaire while waiting for updates.",
  "sudo apt-get install girlfriend... E: Unable to locate package",
  "Windows: Safe Mode is still dangerous.",
  "Linux: You break it, you get to keep both pieces.",
  "Windows is like a bad roommate. Eats all your RAM.",
  "Linux: Why click when you can type 50 words a minute?",
  "Windows defragmentation: The original loading screen.",
  "Linux: The only place where zombies and orphans are harmless.",
  "Windows: Press any key to continue... Where is the ANY key?",
  "Linux: Because the command line is sexier than a GUI.",
  "Windows: It's not crashing, it's taking a break.",
  "I dual-boot Windows for games and Linux for actual work.",
  "Linux: Everything is a file. Windows: Everything is a registry entry.",
  "Windows error: Operation completed successfully.",
  "Linux users don't need anti-virus, they are the root.",
  "Windows: The best way to download a Linux ISO.",
  "Linux: 50 shades of terminal themes.",
  "Windows: Your PC ran into a problem. Just one?",
  "Linux: Compiling... Compiling... Done.",
  "Windows: Because who needs control over their hardware?",
  "Linux: grep, awk, and sed walk into a bar...",
  "Windows 11: Now with rounded corners on your BSOD.",
  "Linux: I use Arch, btw. (Did I mention that?)",
  "Windows: Do not turn off your computer. *Unplugs it*",
  "Linux: The penguin always wins in the end.",
  "Windows: Where 'Not Responding' is a lifestyle.",
  "Linux: sudo !! - The ultimate spell.",
  "Windows: Candy Crush pre-installed for enterprise productivity.",
  "Linux: Man pages are the only literature I read.",
  "Windows: Forgetting your password means reinstalling.",
  "Linux: Chrooting into a broken system is a rite of passage.",
  "Windows: Requires 64GB storage just to idle.",
  "Linux: Running perfectly on a potato since 1995.",
  "Windows: Are you sure? -> Are you really sure? -> Too late.",
  "Linux: Where free refers to speech and beer.",
  "Windows: Rebooting fixes 99% of problems.",
  "Linux: grep -r 'sense' /windows/ -> No results found.",
  "Windows: Edge is highly recommended. By Edge.",
  "Linux: I'd rather write a bash script than click 3 buttons.",
  "Windows: The C: drive is almost full.",
  "Linux: Root privileges are a pathway to abilities some consider unnatural.",
  "Windows: We couldn't complete the updates. Undoing changes.",
  "Linux: It's pronounced GNU/Linux, actually.",
  "Windows: Memory management? What's that?",
  "Linux: A customized dwm setup is a personality trait.",
  "Windows: Please purchase a license to change your wallpaper.",
  "Linux: /dev/null is my trash can.",
  "Windows: Cortana wants to know your location.",
  "Linux: The terminal is dark and full of terrors.",
  "Windows: Blue screens are just surprise color palettes.",
  "Linux: Regular expressions are my native language.",
  "Windows: Checking for a solution to the problem... *Never finds one*",
  "Linux: Open source means I can fix it myself. (I won't).",
  "Windows: The registry is a fragile house of cards.",
  "Linux: Where the community is your tech support.",
  "Windows: Forced updates during a presentation.",
  "Linux: Because real hackers don't use mice.",
  "Windows: Requires a third-party app to unzip a rar file.",
  "Linux: tar -xvf - Because nobody remembers the flags.",
  "Windows: Troubleshooting... Could not identify the problem.",
  "Linux: My window manager takes 2MB of RAM.",
  "Windows: This PC cannot run Windows 11. Thank God.",
  "Linux: Pacman is not just an arcade game.",
  "Windows: Internet Explorer's only purpose was downloading Chrome.",
  "Linux: Everything works perfectly until you try Bluetooth.",
  "Windows: A labyrinth of control panels.",
  "Linux: Wayland is the future. (It has been for 10 years).",
  "Windows: Let's finish setting up your PC. (It's been 5 years).",
  "Linux: I don't use a desktop environment, just TTY.",
  "Windows: Antimalware Service Executable using 90% CPU.",
  "Linux: Where printers are the final boss.",
  "Windows: Your license will expire soon.",
  "Linux: I compiled this joke from source.",
  "Windows: The system tray is a mess.",
  "Linux: Systemd vs SysVinit - The eternal holy war.",
  "Windows: Safely Remove Hardware - Living on the edge.",
  "Linux: Modprobe is my middle name.",
  "Windows: Desktop icons are a sign of weakness.",
  "Linux: Emacs is a great OS, lacking only a good text editor.",
  "Windows: Preparing Windows. Do not turn off your computer.",
  "Linux: My dotfiles are on GitHub.",
  "Windows: Home edition is just a demo.",
  "Linux: Permission denied. *Types sudo* Oh, apologies my lord.",
  "Windows: The recycle bin is full of Edge shortcuts.",
  "Linux: Audio setup? PulseAudio, ALSA, Jack, PipeWire...",
  "Windows: Getting Windows ready.",
  "Linux: Running a server from a 10-year-old laptop.",
  "Windows: You need permission from SYSTEM to edit this file.",
  "Linux: Root has no masters.",
  "Windows: Windows has detected a hard disk problem.",
  "Linux: Ext4 is solid. Btrfs is adventurous.",
  "Windows: Searching for files... 10 years later...",
  "Linux: find . -name 'joke' - It's instant.",
  "Windows: An app default was reset.",
  "Linux: The sheer joy of a successful boot.",
  "Windows: Visual C++ Redistributable 2005, 2008, 2010, 2012, 2013, 2015...",
  "Linux: Shared libraries just work.",
  "Windows: Some settings are managed by your organization.",
  "Linux: The kernel panic is just a feature.",
  "Windows: To free up disk space... deletes your files.",
  "Linux: /home is where the heart is.",
  "Windows: Fast startup is a lie.",
  "Linux: Because a GUI is just overhead.",
  "Windows: This program has performed an illegal operation.",
  "Linux: The penguin is mightier than the flag.",
  "Windows: Action Center has 99 notifications about Defender.",
  "Linux: I don't need a UI, I have grep.",
  "Windows: Restart required. Always.",
  "Linux: 0 days since last distro hop.",
  "Windows: Your PC ran into a problem and needs to restart.",
  "Linux: I wrote a bash script to tell this joke.",
  "Windows: Updating your system... 1% for 3 hours.",
  "Linux: Sudo make me a laugh.",
  "Windows: The ultimate bootloader... for Linux.",
  "Linux: It's free, but your time isn't.",
  "Windows: Where you pay for bugs.",
  "Linux: Open source, open mind.",
  "Windows: We're getting everything ready for you.",
  "Linux: The terminal is my canvas.",
  "Windows: Because who doesn't love telemetry?",
  "Linux: Where privacy is not an illusion.",
  "Windows: The ultimate patience tester.",
  "Linux: The reason I have a mechanical keyboard.",
  "Windows: Do you want to allow this app to make changes?",
  "Linux: The only limit is hardware compatibility.",
  "Windows: You don't have permission to save in this location.",
  "Linux: Because I can.",
  "Windows: Searching for a solution... *Cancels immediately*",
  "Linux: Where every update is a leap of faith.",
  "Windows: The true definition of bloatware.",
  "Linux: The OS that respects you.",
  "Windows: We couldn't connect to update service. Good.",
  "Linux: The community is the manual.",
  "Windows: Your Windows license will expire soon.",
  "Linux: The power of the command line compels you.",
  "Windows: An unexpected error occurred.",
  "Linux: Where customization has no limits.",
  "Windows: This app is preventing shutdown.",
  "Linux: Because I like knowing what my computer is doing.",
  "Windows: We're setting up a few more things.",
  "Linux: OS of choice for supercomputers and smart fridges.",
  "Windows: Your PC is not protected.",
  "Linux: Where free means freedom.",
  "Windows: We found some updates.",
  "Linux: The ultimate playground for nerds.",
  "Windows: Restart to apply updates. No thanks.",
  "Linux: The only OS that truly feels like home.",
  "Linux is like a box of Legos. Windows is a pre-glued model.",
  "Windows: Where every file extension hidden by default.",
  "Linux: The best way to learn how your computer works.",
  "Windows: Do you want to send an error report to Microsoft?",
  "Linux: The kernel is my shepherd, I shall not crash.",
  "Windows: An unexpected error is keeping you from copying this file.",
  "Linux: Who needs a mouse when you have keyboard shortcuts?",
  "Windows: Re-evaluating your life choices during a forced update.",
  "Linux: Fast, reliable, and completely confusing to your parents.",
  "Windows: Where 'Plug and Play' means 'Plug and Pray'.",
  "Linux: It's not a religion, but we do have a penguin mascot.",
  "Windows: Why do I have 15 versions of Visual C++?",
  "Linux: You don't have to pay $130 for an OS.",
  "Windows: The OS that cries wolf.",
  "Linux: Where 'grep' is a verb.",
  "Windows: Please wait while Windows configures updates.",
  "Linux: The terminal is not scary, it's efficient.",
  "Windows: Have you tried turning it off and on again?",
  "Linux: The OS that actually listens to you.",
  "Windows: A maze of hidden control panels.",
  "Linux: Because life is too short for slow boot times.",
  "Windows: When in doubt, format C:.",
  "Linux: Where 'open source' is a philosophy.",
  "Windows: The OS that loves to interrupt fullscreen apps.",
  "Linux: Customizable down to the kernel compilation.",
  "Windows: A never-ending battle against background telemetry.",
  "Linux: Because I prefer to own my hardware."
];
